#!/bin/bash


function get_help() {

    figlet nstk
    echo "nstk, a simple cli app to transfer books to a kindle paperwhite"
    echo "usage $0 [options]"
    echo
    echo "options:"
    echo "-h --help        show this help message and exit"
    echo "-t --transfer    transfer a file directly to the kindle"
    echo "-c --convert     convert a file (.pdf, .epub) to an amazon kindle .azw3 file"



}


function transfer()
{
    mount -L "Kindle" --mkdir /mnt/kindle
    wait 1
    echo transferring files to kindle...

}

if [[ $EUID -ne 0  ]]
then
    get_help
    echo "This program must be run with root/sudo privileges"
    exit


elif [[ $1 == -h || $1 == --help ]]
then
   get_help 

   elif  [[ $# = 0 ]]
   then
    get_help

elif [[ $1 == -t || $1 == --transfer ]]
then
transfer

else
    echo "ERROR $1 not a valid command"
    get_help
    
    fi

  exit
